# Packet
"tc" = "Packet"
"tc.E" = "pos"
"tc.J" = "data"
"tc.b(Z)I" = "g1"
"tc.b(II)V" = "p1"
"tc.d(Z)B" = "g1b"
"tc.l(I)I" = "g2"
"tc.b(BI)V" = "p2"
"tc.d(B)I" = "g2b"
"tc.f(I)I" = "g3"
"tc.b(IB)V" = "p3"
"tc.b(I)I" = "g4"
"tc.c(BI)V" = "p4"
"tc.i(I)J" = "g8"
"tc.a(ZJ)V" = "p8"
"tc.d(I)I" = "gsmart"
"tc.g(Z)I" = "gsmarts"
"tc.b(IZ)V" = "psmarts"
"tc.f(B)I" = "gvarint"
"tc.f(II)V" = "psize1"
"tc.d(BI)I" = "addcrc"
"tc.a(BI[II)V" = "tinydec"
"tc.a(Ljava/math/BigInteger;Ljava/math/BigInteger;B)V" = "rsaenc"
"tc.a(III[B)V" = "gdata"
"tc.a(I[BII)V" = "pdata"
"tc.a(Lva;B)V" = "pjstr"
"tc.j(I)Lva;" = "gjstr"

# RSA key
"fb.i" = "modulus"
"r.b" = "exponent"

# Js5
"he.a([IBI)Z" = "unpack"

# Player
"me" = "Player"
"me.a(Ltc;Z)V" = "decodeAppearance"

# Misc

"ha.a(IIILme;)V" = "decodePlayerExtendedInfo"